data = read.csv("household_power_consumption_hw.txt", sep=";")
png("plot2.png")
plot(strptime(paste(data$Date,data$Time), format = "%d/%m/%Y %H:%M:%S"), as.numeric(data$Global_active_power), type="n", main="", xlab="", ylab="Global Active Power (kilowatts)")
lines(strptime(paste(data$Date,data$Time), format = "%d/%m/%Y %H:%M:%S"), as.numeric(data$Global_active_power))
dev.off()
